[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "echo 'Please deploy individual services from their directories'"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "frontend"
source = "services/frontend"

[[services]]
name = "backend" 
source = "services/backend"

[[services]]
name = "api-gateway"
source = "services/api-gateway"