#!/bin/bash

echo "🔐 Railway Environment Variables Setup"
echo "====================================="
echo ""
echo "Copy and paste these environment variables in Railway Dashboard:"
echo ""
echo "=== FRONTEND SERVICE ==="
echo "NEXT_PUBLIC_API_URL=\${{RAILWAY_PUBLIC_DOMAIN}}"
echo "BACKEND_URL=http://backend.railway.internal:8080"
echo "API_GATEWAY_URL=http://api-gateway.railway.internal:4000"
echo ""
echo "=== BACKEND SERVICE ==="
echo "OPENAI_KEY=<your-openai-key>"
echo "ANTHROPIC_KEY=<your-anthropic-key>"
echo "GATEWAY_URL=http://api-gateway.railway.internal:4000"
echo "WATCH_MODE=true"
echo "NODE_ENV=production"
echo ""
echo "=== API GATEWAY SERVICE ==="
echo "OPENAI_KEY=<your-openai-key>"
echo "ANTHROPIC_KEY=<your-anthropic-key>"
echo "DEEPSEEK_API_KEY=<your-deepseek-key>"
echo "LITELLM_MASTER_KEY=<generate-secure-random-string>"
echo "GATEWAY_URL=http://0.0.0.0:4000"
echo ""
echo "📌 Steps:"
echo "1. Go to https://railway.app/new"
echo "2. Select 'Deploy from GitHub repo'"
echo "3. Choose sdem88/parallel-ai-agents-railway"
echo "4. Add these environment variables to each service"